### ISSUE TITLE
Exported HTML looks different on Windows and Mac

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#100]
Flagged by a Google trainer

<img width="1423" alt="screen shot 2018-06-12 at 2 22 15 pm" src="https://user-images.githubusercontent.com/3636117/41337105-34403da0-6ee6-11e8-87ce-2e36409179d8.png">
<img width="1422" alt="screen shot 2018-06-12 at 10 24 27 am" src="https://user-images.githubusercontent.com/3636117/41337109-367f3d3c-6ee6-11e8-8f1a-3adbee4bb7e8.png">

**Comment by annapowellsmith** [comment]
Can reproduce on the Windows machine here: the `style.css` file is 404ing, even though it exists in the zipfile.

Confusingly, a downloaded visualisation on OSX has a `styles.css` file not `style.css`. #confused

**Comment by daanlouter** [comment]
<img width="118" alt="screen shot 2018-06-13 at 09 03 13" src="https://user-images.githubusercontent.com/3636117/41337967-a5ea0cf4-6ee8-11e8-936a-7a096347ce9b.png">

My version just has a `style.css`?

**Comment by annapowellsmith** [comment]
<img width="305" alt="screen shot 2018-06-13 at 09 04 21" src="https://user-images.githubusercontent.com/78156/41338022-cf7de676-6ee8-11e8-82ec-ace5fa8a5bc9.png">

I'll look at the code...

**Comment by annapowellsmith** [comment]
On reflection, I guess this is about what the template chooses to call its files. 

Anyway, I think the Windows issue is about how it treats local files. We probably want to add a README in the download bundle explaining that people should avoid serving these as local files.

**Comment by annapowellsmith** [comment]
Yeah, works fine if run with `http-server` on the Windows machine. I've opened https://github.com/kiln/flourish/issues/1674
