### ISSUE TITLE
Option to style x-axis labels

### ISSUE THREAD

**Issue by micycle** [kiln/template-horserace#102]
Requested by a user https://secure.helpscout.net/conversation/620331920/979?folderId=1390901

Be good if this was consistent across templates!

**Comment by daanlouter** [comment]
👍 

This was requested multiple times

**Comment by daanlouter** [comment]
Done in https://github.com/kiln/template-horserace/pull/104

**Comment by daanlouter** [comment]
Reopening, as the label rotation doesn't seem to work. @JulienAssouline, might be worth double checking state property names
