### ISSUE TITLE
Add background:none

### ISSUE THREAD

**Issue by keriley** [kiln/template-horserace#126]
Bloomberg Law flagged this in an email that you *have to* specify a background color. Not sure if there's anything technical blocking this (save first implementing the layout module).

**Comment by timbrock** [comment]
This should probably be part of the layout tab of the layout module :|.

**Comment by theduncanclark** [comment]
Can you open an issue in the flourish-layout @katie and close this one? Might be worth doing it as  "More background options" as "None" is one thing we should add but I was always imagining we'd also support background images, gradients, etc eventually.
