### ISSUE TITLE
Option to limit the number of entrants within visualisation

### ISSUE THREAD

**Issue by RichardFlourish** [kiln/template-horserace#132]
Minor feature request, not very important.

An option to limit the number of entrants within the visualisation, similar to the Bar Chart Race, which would then allow entrants to drop in and out of the race depending on their performance.

(no urgency or customer priority to this from my POV)

**Comment by daanlouter** [comment]
I think this already possible with the "max y scale" settings. Is this what you mean?

**Comment by RichardFlourish** [comment]
So, it is, thanks Daan! :-)
