### ISSUE TITLE
We should have "higher scores win" sample data

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-horserace#18]
"Lower scores win" is a bit of a special case. It's great that we are supporting it, but we should probably have more typical sample data such as political poll or football league. Needs to be something where there's quite a lot of variety in the ranks as well as the scores. We could maybe use one of the earlier Google search datasets.

**Comment by daanlouter** [comment]
Have an example of favourability ratings here: https://public.flourish.studio/visualisation/1433/ - and a football table here: https://public.flourish.studio/visualisation/1434/

**Comment by annapowellsmith** [comment]
Fixed in https://github.com/kiln/template-horserace/commit/35574335cb0356f515949b3c74f601ebe45381c7
