### ISSUE TITLE
Always move label to end of the line

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#21]
Currently the label moves away from the line if the last column value is missing 

<img width="500" alt="screen shot 2017-07-19 at 17 51 51" src="https://user-images.githubusercontent.com/3636117/28379264-fc9a5b4e-6caa-11e7-915f-0bacebda9723.png">

**Comment by theduncanclark** [comment]
Closing this as a subset of the broader discussion of #33.
