### ISSUE TITLE
Option to specify the x-axis scale start/end points – e.g. to lock to zero

### ISSUE THREAD

**Issue by felixmichel** [kiln/template-horserace#24]
If the numbers are low, it would be better to set axis to zero. See screenshot.
<img width="845" alt="bildschirmfoto 2017-09-05 um 11 44 02" src="https://user-images.githubusercontent.com/11921821/30055430-b788504c-922f-11e7-9054-3a485e12fa95.png">

**Comment by theduncanclark** [comment]
Good plan. We should add an optional number setting for the lower value (which defaults to null and is based on the data, i.e. current behaviour), and possibly one for the upper value as well.

**Comment by daanlouter** [comment]
Looking good

**Comment by theduncanclark** [comment]
Looks great but the yml has comments saying "TODO We need nullable column bindings". We now have them! So we should add `optional: true` to these settings.

In fact until we do that it won't work for the main purpose of setting the axis to zero as the code is only applying `if (state.y_axis_min)` which will be false if the value is zero.

**Comment by daanlouter** [comment]
Fixed that
