### ISSUE TITLE
What can we do about long labels on x-axis?

### ISSUE THREAD

**Issue by felixmichel** [kiln/template-horserace#26]
Germans love long words! Doing the horserace for the German election I used the standard term (Bundestagswahl) which is already too long. What can we do about it?
<img width="1218" alt="bildschirmfoto 2017-09-05 um 11 49 37" src="https://user-images.githubusercontent.com/11921821/30055623-53f7a036-9230-11e7-8cbf-7e437e380708.png">

**Comment by theduncanclark** [comment]
You can already increase the top margin if you want to accommodate the longer words, I think.

**Comment by theduncanclark** [comment]
It's possible we should also auto-truncate words (i.e. Bundesta…) if they don't fit in the specified margin, but maybe we wait until users tell us they want this?

**Comment by felixmichel** [comment]
I think the margin is a good solution.
