### ISSUE TITLE
Icons don’t show up on downloaded image

### ISSUE THREAD

**Issue by robinhouston** [kiln/template-horserace#27]
This may be a Flourish issue rather than a template issue, but I thought we should record it somewhere.

![copy of copy of horsie horsie don t you stop](https://user-images.githubusercontent.com/103315/30164618-0453ae20-93d5-11e7-8c00-d2ae8339390a.png)

**Comment by daanlouter** [comment]
We have a duplicate issue here, with more discussion: https://github.com/kiln/template-horserace/issues/36
