### ISSUE TITLE
Better handle empty columns and cells

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#33]
If a cell is empty, the position in the chart is really weird. should probably just ignore that value. If a whole column is empty, it will break the viz.

<img width="234" alt="bildschirmfoto 2017-10-02 um 17 22 53" src="https://user-images.githubusercontent.com/3636117/31085141-4887d842-a78e-11e7-8f43-970d72e8a2be.png">
<img width="181" alt="bildschirmfoto 2017-10-02 um 17 22 36" src="https://user-images.githubusercontent.com/3636117/31085147-4ae8c1f0-a78e-11e7-97aa-bce87a6d1aa6.png">

**Comment by daanlouter** [comment]
I took a look at this, but can't really get my head around how the animation stuff works. Would be great if @robinhouston or @theduncanclark could take a look at this.

If a stage has no value, it shouldn't update the labels position, the label should stick to the previous valid stage. Ideally, when it reaches a stage that has data, after being "stuck" in a null-column, it shouldn't transition to that point.

**Comment by robinhouston** [comment]
Sure, I can look at this.

**Comment by theduncanclark** [comment]
I'll leave it to you then @robinhouston. If I remember right, we weren't handling blanks at all before, then I added a `defined` check to the line generator to create the appropriate gaps.

**Comment by daanlouter** [comment]
The labels still jump off the screen on an empty stage for me

<img width="509" alt="screen shot 2017-10-02 at 18 44 57" src="https://user-images.githubusercontent.com/3636117/31091131-d53247ba-a7a1-11e7-93dd-a4bf7b455267.png">

**Comment by robinhouston** [comment]
Where do you think they should go?

Are you assuming it’ll join up across the gap, instead of leaving a space?

**Comment by daanlouter** [comment]
I was thinking the label should always stick with last valid value on the _left_ of the null column.
```
stage 1, stage 2, stage 3, stage 4
3, , ,1
```
So if we're at stage 2 or 3, the label should be at stage 1. Ideally if the label goes from stage 1 to stage 4 (jumping the gap), it shouldn't transition. What do you think of this?

**Comment by robinhouston** [comment]
I get this error if I add a new row that just has a name and no values:

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at SVGCircleElement.<anonymous> (update_graphic.js:59)
    at SVGCircleElement.<anonymous> (attr.js:29)
    at V.la [as each] (each.js:5)
    at V.ha [as attr] (attr.js:53)
    at gi (update_graphic.js:59)
    at wi (update_graphic.js:160)
    at Ei (update_graphic.js:214)
    at Pi (update.js:6)
    at Object.Ui [as draw] (draw.js:9)
    at preview:17
```

**Comment by daanlouter** [comment]
@robinhouston That last bug is fixed in https://github.com/kiln/template-horserace/commit/9e1d89f93d8b908161af2248f41dac0e2a26b934
