### ISSUE TITLE
See if pics work in downloaded image once file-uploads are implemented

### ISSUE THREAD

**Issue by robinhouston** [kiln/template-horserace#36]
I guess we should set `image_download: false` if this can’t easily be made to work.

![snapshot-1507807174500](https://user-images.githubusercontent.com/103315/31493619-e931db38-af47-11e7-8561-fedccbc5d325.png)

**Comment by theduncanclark** [comment]
Interesting case where it works except for one feature.

Should we consider a class you can add in templates to elements to exclude from the image?

**Comment by theduncanclark** [comment]
(Grabbing the svg would be useful here in some cases even if the images don't work. Umm.)

**Comment by robinhouston** [comment]
Would it be hard to fix this feature? If not, maybe that’s the answer.

**Comment by theduncanclark** [comment]
Not sure. @micycle? I have a memory you said it would be tricky…

**Comment by robinhouston** [comment]
Is it because the images are cross-domain?

If so then I guess the Flourish image store will fix this.

**Comment by theduncanclark** [comment]
Good point!

**Comment by theduncanclark** [comment]
For now I've turned image downloads off (e666bfa). The hope is that this is work properly when we have file uploads sorted, so I'll update the issue title accordingly.

**Comment by JulienAssouline** [comment]
this still doesn't work with the new image paths.
![snapshot-1534765695179](https://user-images.githubusercontent.com/17466947/44339073-000c2380-a44e-11e8-87a7-b1426d6aaaf0.png)

**Comment by daanlouter** [comment]
This will be fixed once https://github.com/kiln/flourish/pull/1892 is deployed

**Comment by daanlouter** [comment]
Actually let's keep open till we can remove` image_download: false`
