### ISSUE TITLE
Mobile styles

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#37]
It doesn't look great on mobile. Especially when having long labels and big circles.

**Comment by theduncanclark** [comment]
Maybe below a certain size it the whole SVG should be scaled down a bit?

**Comment by daanlouter** [comment]
Yeah, or at least the labels/circles. Nice idea

**Comment by daanlouter** [comment]
I improved the labels and circles for mobile in https://github.com/kiln/template-horserace/commit/72685735c5f0e7e6e3a3e089c66e6cee9d85e722
