### ISSUE TITLE
Strange behavior in horserace regarding suffix / labels outside circle

### ISSUE THREAD

**Issue by felixmichel** [kiln/template-horserace#38]
![horserace_bug](https://user-images.githubusercontent.com/11921821/31604462-af4071a4-b263-11e7-979b-3055989c1110.gif)

**Comment by daanlouter** [comment]
🤔

**Comment by daanlouter** [comment]
This is so weird! Have made a separate issue for this, as I think it's not template specific https://github.com/kiln/flourish/issues/774

**Comment by theduncanclark** [comment]
I think we've concluded this is Flourish issue and nothing to do with the template so let's close it here.
