### ISSUE TITLE
Setting to stop lines disappearing entirely when a line is selected

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-horserace#43]
I think in general it's nicer to see a highlighted with the others faint. Currently you get this on mouseover but if you select a line with click – e.g. to capture it in the story editor – the others disappear entirely. This either shouldn't happen or there should be a setting to provide both options.

**Comment by annapowellsmith** [comment]
+1. I think it just shouldn't happen, rather than being an extra setting.

**Comment by daanlouter** [comment]
Fixed in https://github.com/kiln/template-horserace/commit/39c278420c7a734062a6880b8123b34220d03dfa
