### ISSUE TITLE
Bring marker for hovered line to top of stack

### ISSUE THREAD

**Issue by timbrock** [kiln/template-horserace#45]
So it is fully visible, unlike here.

<img width="1007" alt="screen shot 2017-10-27 at 14 29 53" src="https://user-images.githubusercontent.com/7906373/32106413-789d45d2-bb23-11e7-958f-4a6e7daf589e.png">

**Comment by theduncanclark** [comment]
Ah, didn't see your self-assign @timbrock. Just did a PR for this one!

**Comment by theduncanclark** [comment]
Probably worth a careful test in story editor etc

**Comment by timbrock** [comment]
> Ah, didn't see your self-assign @timbrock. Just did a PR for this one!

S'fine, I hadn't actually looked at it.
