### ISSUE TITLE
Rounding on numbers

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-horserace#5]
We should limit number of decimal places in the circles to avoid things like this:

![image](https://user-images.githubusercontent.com/9587433/27131776-0f48342c-5104-11e7-893f-fdcf93a92f33.png)

**Comment by daanlouter** [comment]
But this number comes directly from the dataset, right?

**Comment by theduncanclark** [comment]
Yeah, true, but nothing to stop us limiting the decimal places. If the raw data has loads of decimals it would be annoying to have to do that manually, no?

**Comment by daanlouter** [comment]
Agree, but have slight worries about this, because:

- Maybe these values are somehow intentional. And how would we decide if we completely round, or keep 1,2 or 3 decimal numbers.?
- Adding this invisible "magic" might create the impression we are doing rounding in all visualisations. Keeping it "dumb" makes people realise they need to clean up their data before using Flourish.

**Comment by theduncanclark** [comment]
In some templates we have a setting – max number of decimal places to show. We could default it to 1 or 2 and in the very unlikely case someone wants more they could do this in the settings?

**Comment by daanlouter** [comment]
That sounds okay. But in general I still think we should only round numbers that the code calculates/generates, not if the numbers come straight from the dataset.

I just added this setting to the ticker template too. Which makes me think we should have some common/global functions for this?

**Comment by theduncanclark** [comment]
> should have some common/global functions for this?

Good question! The connections globe mode is my normal one:

```
function getFormattedScore(val) {
	var rounder = Math.pow(10, state.decimal_places),
	    rounded = Math.round(val * rounder)/rounder;
	return state.val_prefix + d3.format(",")(rounded) + state.val_prefix;
}
```

You used to be able to do this with D3.round but I think Mike removed it due a problem that no longer exists and it might reappear one day. D3 format doesn't support it as you end up with training zeros which we don't want. Yes, maybe we should think about some Flourish-wide functions for this kind of thing – thought also not hard to copy or write each time. @robin – any view?

> in general I still think we should only round numbers that the code calculates/generates, not if the numbers come straight from the dataset.

I see what you mean but don't agree. Think of taking a big CSV from a database with eight decimal places and mapping it. When you hover over a country you want to see a rounded value, not whatever's in the spreadsheet. And although we _could_ ask people to sort this out in advance, it's asking them to do a lot of data processing for no obviously reason every time they want to use the template, which makes it harder for them to make Flourish graphics. Also if it's in the template settings you can fine tune it for different datasets which is nice.
