### ISSUE TITLE
Changing the score column range throws an error

### ISSUE THREAD

**Issue by timbrock** [kiln/template-horserace#51]
... with the default data.

**Comment by daanlouter** [comment]
@theduncanclark can probably fix this much quicker than me, as I don't understand this code fully. But let me know if you dont have time Duncan, and I can take a look.

**Comment by timbrock** [comment]
I _think_ we've just worked this out.

**Comment by robinhouston** [comment]
Fixed by 8ecd4bf47e0539213aa06a5c24a79e4ace768492.
