### ISSUE TITLE
Key data binding by name?

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-horserace#57]
Feels a bit odd to animate between unrelated datasets. E.g. between slides 2 and 3 in this Flourish classic:

https://public.flourish.studio/story/1197/

**Comment by timbrock** [comment]
I was just wondering about this.

**Comment by daanlouter** [comment]
Fixed by https://github.com/kiln/template-horserace/commit/02a1792bedd483d80b4b9692029de5caa6dbc0cf
