### ISSUE TITLE
Add setting for end circle border color 

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#58]
<img width="243" alt="screen shot 2018-01-29 at 10 42 17" src="https://user-images.githubusercontent.com/3636117/35506435-275e2742-04e1-11e8-8fc1-54249ed99d58.png">

**Comment by theduncanclark** [comment]
Or it could just inherit the line colour possibly?

**Comment by daanlouter** [comment]
Fixed in https://github.com/kiln/template-horserace/commit/7be041413501c6dcb859fd56bd2cf95b735edc62
