### ISSUE TITLE
Height resize doesn't work properly on iOS embed

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#66]
☹️

![image uploaded from ios](https://user-images.githubusercontent.com/3636117/36103097-4c42da28-1006-11e8-9f26-e94d20712dc7.png)

**Comment by daanlouter** [comment]
This is a very weird issue. Apparently, the resize event is not being triggered consistently. 
Inside the template I've monitored the height of the body in an interval. It moves from 150px to 450px, however the resize event is never being triggered. When I go into dev tools and change the height of the iframe manually, it _does_ trigger the resize event.

I've fixed it now by setting a min height to the svg of 450 pixels. But it'd be good to look this over with @micycle tomorrow, to see if this would be fixed in the new embed logic.

**Comment by theduncanclark** [comment]
For the record, I've seen similar things with the time-maps – and could be the same thing that has caused problems elsewhere, e.g. with the Sankey animations.

**Comment by daanlouter** [comment]
Yes, have tested with a couple of templates yesterday, all the same behaviour. Same for slope chart.

**Comment by micycle** [comment]
The new approach will at least mean that the iframe is instantiated with a sensible height, though if window resize events are not picked up then it won't change after that

**Comment by daanlouter** [comment]
@micycle resize events do get picked up eventually. Just not straight after load, it seems.

**Comment by micycle** [comment]
Good, in that case new approach should be much better

**Comment by daanlouter** [comment]
Fixed in https://github.com/kiln/template-horserace/commit/7be041413501c6dcb859fd56bd2cf95b735edc62
