### ISSUE TITLE
Mismatch between color palettes and those exposed in template.yml

### ISSUE THREAD

**Issue by timbrock** [kiln/template-horserace#74]
schemeSet1, schemeSet2 and schemeSet3 are all included in color.js but there's no option to pick them in template.yml. Is this a mistake or for backwards compatibility?

**Comment by timbrock** [comment]
From talking to @daanlouter, I think these are no longer required. Should probably be deleted just before the next time we decide to retire and replace the template.

**Comment by daanlouter** [comment]
This is fixed now I think
