### ISSUE TITLE
Rankings do not properly account for equals

### ISSUE THREAD

**Issue by micycle** [kiln/template-horserace#79]
e.g if there are a couple of 1st= entries, then the ranking for the 3rd placed person will show as "2", etc

**Comment by timbrock** [comment]
Bump. This is in the default data and we should fix this.

<img width="107" alt="screen shot 2018-08-23 at 17 26 40" src="https://user-images.githubusercontent.com/7906373/44538669-f6a6e380-a6f9-11e8-922c-68573630f1a1.png">

**Comment by annapowellsmith** [comment]
See my comment on https://github.com/kiln/template-slope-chart/issues/68#issuecomment-415489052

**Comment by timbrock** [comment]
If you have a six-horse-race and you come last then you place 6th. We should probably offer options, but the [Standard competition ranking](https://en.wikipedia.org/wiki/Ranking#Standard_competition_ranking_(%221224%22_ranking)) should definitely be default, imho.

**Comment by annapowellsmith** [comment]
I don't disagree - just don't think it's as high-priority as other issues :) Would be a good Friday project though!

**Comment by timbrock** [comment]
[Too late](https://github.com/kiln/template-horserace/pull/106).

**Comment by daanlouter** [comment]
Ha, missed this discussion. Just reviewed the change and I personally think it looks quite odd that there's a gap at the 5th spot now.

<img width="113" alt="screen shot 2018-08-27 at 10 52 23" src="https://user-images.githubusercontent.com/3636117/44650724-b42a2300-a9e7-11e8-8496-588a70233b39.png">
