### ISSUE TITLE
Min score setting not working

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-horserace#80]
I put in data with a negative minimum number. The axis starts at zero by default (already a bit odd). When I tried to override it with -1000, it says:

![image](https://user-images.githubusercontent.com/9587433/37030449-eaacfa26-2132-11e8-8bb2-83ea1b9d43dc.png)

**Comment by daanlouter** [comment]
Have changed default values, but can't reproduce this problem. Can you check and see if it happens again?

BTW it would be nice to have score/rank settings as conditional settings, but didn't do that as the scores/ranks can be changed from within visualisations (and settings panel wouldn't update accordingly).
