### ISSUE TITLE
Labels can overflow (and margins are not applied) on mobile

### ISSUE THREAD

**Issue by danielgavrilov** [kiln/template-horserace#89]
E.g. 

<img width="390" alt="screenshot 2018-04-24 13 13 29" src="https://user-images.githubusercontent.com/1308115/39186125-5e0938fe-47c1-11e8-9ede-c79140835d67.png">

**Comment by daanlouter** [comment]
Fixed in https://github.com/kiln/template-horserace/commit/67bdbda17adae30407246a38e4d986b299400021
