### ISSUE TITLE
No-horses-selected versus all-horses-selected behave differently...

### ISSUE THREAD

**Issue by timbrock** [kiln/template-horserace#98]
... but look identical

No horses selected:
<img width="1071" alt="screen shot 2018-05-22 at 17 12 08" src="https://user-images.githubusercontent.com/7906373/40375472-9e08d3c8-5de3-11e8-9082-813604cda199.png">

All horses selected
<img width="1074" alt="screen shot 2018-05-22 at 17 12 28" src="https://user-images.githubusercontent.com/7906373/40375484-a6bcb75a-5de3-11e8-909d-899bb6d32ee0.png">

Click Angela in the former case:
<img width="1070" alt="screen shot 2018-05-22 at 17 16 27" src="https://user-images.githubusercontent.com/7906373/40375675-24b388aa-5de4-11e8-9195-42dcc6e3a335.png">

Click Angela in the latter case:
<img width="1073" alt="screen shot 2018-05-22 at 17 16 37" src="https://user-images.githubusercontent.com/7906373/40375689-352f270c-5de4-11e8-9d9b-8d84cb263dbc.png">

This feels really weird to me.

**Comment by daanlouter** [comment]
Though I agree this is not perfect. This feels so edge case and minor and would take quite a bit of time to re-think and implement.

Please re-open if you know of a quick solution for this.
